site_name: 我的知识库
site_url: ""
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
  - admonition
nav:
  - 首页: index.md
  - 跨终端 Markdown 知识库方案对比.md 
  - ProfControl AGV仓储仿真系统 项目需求设计书.md
